"""confirm_dismiss_columns

Revision ID: 43bc4967a755
Revises: 47feee03cd82
Create Date: 2026-08-04 20:45:31.570085

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '43bc4967a755'
down_revision = '47feee03cd82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extraction_results', sa.Column('category_confirmed', sa.String(length=100), nullable=True))
    op.add_column('extraction_results', sa.Column('dismissed_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extraction_results', 'dismissed_reason')
    op.drop_column('extraction_results', 'category_confirmed')
    # ### end Alembic commands ###
