"""unique_r2_key_idempotency

Revision ID: 47feee03cd82
Revises: 71d4bcb7ea26
Create Date: 2026-07-28 21:29:09.359640

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '47feee03cd82'
down_revision = '71d4bcb7ea26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_imported_emails_r2_key'), 'imported_emails', ['r2_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_imported_emails_r2_key'), 'imported_emails', type_='unique')
    # ### end Alembic commands ###
