"""initial_schema

Revision ID: 71d4bcb7ea26
Revises: 
Create Date: 2026-07-27 21:48:14.385449

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '71d4bcb7ea26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aliases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('alias_hash', sa.String(length=64), nullable=False),
    sa.Column('external_user_id', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('emails_received', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aliases'))
    )
    op.create_index(op.f('ix_aliases_alias_hash'), 'aliases', ['alias_hash'], unique=True)
    op.create_index(op.f('ix_aliases_external_user_id'), 'aliases', ['external_user_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys')),
    sa.UniqueConstraint('key_hash', name=op.f('uq_api_keys_key_hash'))
    )
    op.create_table('category_feedback_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('extraction_id', sa.Uuid(), nullable=True),
    sa.Column('merchant_normalized', sa.String(length=255), nullable=False),
    sa.Column('category_confirmed', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category_feedback_log'))
    )
    op.create_index(op.f('ix_category_feedback_log_extraction_id'), 'category_feedback_log', ['extraction_id'], unique=False)
    op.create_index(op.f('ix_category_feedback_log_merchant_normalized'), 'category_feedback_log', ['merchant_normalized'], unique=False)
    op.create_table('extraction_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sender_domain', sa.String(length=255), nullable=False),
    sa.Column('patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('email_type', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extraction_templates')),
    sa.UniqueConstraint('sender_domain', name=op.f('uq_extraction_templates_sender_domain'))
    )
    op.create_table('import_audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('previous_status', sa.String(length=32), nullable=True),
    sa.Column('new_status', sa.String(length=32), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_audit_logs'))
    )
    op.create_index(op.f('ix_import_audit_logs_email_id'), 'import_audit_logs', ['email_id'], unique=False)
    op.create_table('imported_emails',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('alias_hash', sa.String(length=64), nullable=False),
    sa.Column('r2_key', sa.String(length=512), nullable=True),
    sa.Column('from_address', sa.String(length=320), nullable=True),
    sa.Column('resolved_sender_domain', sa.String(length=255), nullable=True),
    sa.Column('sender_source', sa.String(length=16), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('message_id', sa.String(length=998), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('processing_errors', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_imported_emails'))
    )
    op.create_index(op.f('ix_imported_emails_alias_hash'), 'imported_emails', ['alias_hash'], unique=False)
    op.create_index(op.f('ix_imported_emails_status'), 'imported_emails', ['status'], unique=False)
    op.create_index('uq_imported_emails_alias_message', 'imported_emails', ['alias_hash', 'message_id'], unique=True, postgresql_where="message_id IS NOT NULL AND message_id != ''")
    op.create_table('merchant_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pattern', sa.String(length=255), nullable=False),
    sa.Column('match_type', sa.String(length=16), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('confirmation_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchant_rules'))
    )
    op.create_table('webhook_config',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('webhook_url', sa.String(length=1024), nullable=False),
    sa.Column('webhook_secret_encrypted', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_config'))
    )
    op.create_table('webhook_outbox',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_url', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_outbox'))
    )
    op.create_index(op.f('ix_webhook_outbox_next_attempt_at'), 'webhook_outbox', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_webhook_outbox_status'), 'webhook_outbox', ['status'], unique=False)
    op.create_table('email_classifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email_id', sa.Uuid(), nullable=False),
    sa.Column('is_financial', sa.Boolean(), nullable=False),
    sa.Column('email_type', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['imported_emails.id'], name=op.f('fk_email_classifications_email_id_imported_emails'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_classifications'))
    )
    op.create_index(op.f('ix_email_classifications_email_id'), 'email_classifications', ['email_id'], unique=False)
    op.create_table('extraction_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email_id', sa.Uuid(), nullable=False),
    sa.Column('external_user_id', sa.String(length=255), nullable=False),
    sa.Column('alias_hash', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('currency', sa.CHAR(length=3), nullable=True),
    sa.Column('merchant_raw', sa.Text(), nullable=True),
    sa.Column('merchant_normalized', sa.String(length=255), nullable=True),
    sa.Column('category_suggestion', sa.String(length=100), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('card_last4', sa.CHAR(length=4), nullable=True),
    sa.Column('extraction_confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('confidence_band', sa.String(length=16), nullable=False),
    sa.Column('field_confidences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('method', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('duplicate_confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['imported_emails.id'], name=op.f('fk_extraction_results_email_id_imported_emails'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extraction_results'))
    )
    op.create_index(op.f('ix_extraction_results_email_id'), 'extraction_results', ['email_id'], unique=False)
    op.create_index(op.f('ix_extraction_results_external_user_id'), 'extraction_results', ['external_user_id'], unique=False)
    op.create_index(op.f('ix_extraction_results_fingerprint'), 'extraction_results', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_extraction_results_status'), 'extraction_results', ['status'], unique=False)
    op.create_table('duplicate_matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('extraction_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_type', sa.String(length=32), nullable=False),
    sa.Column('duplicate_confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['extraction_id'], ['extraction_results.id'], name=op.f('fk_duplicate_matches_extraction_id_extraction_results'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_duplicate_matches'))
    )
    op.create_index(op.f('ix_duplicate_matches_extraction_id'), 'duplicate_matches', ['extraction_id'], unique=False)
    op.create_table('extraction_snippets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('extraction_id', sa.Uuid(), nullable=False),
    sa.Column('raw_snippet', sa.Text(), nullable=False),
    sa.Column('snippet_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['extraction_id'], ['extraction_results.id'], name=op.f('fk_extraction_snippets_extraction_id_extraction_results'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extraction_snippets'))
    )
    op.create_index(op.f('ix_extraction_snippets_extraction_id'), 'extraction_snippets', ['extraction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extraction_snippets_extraction_id'), table_name='extraction_snippets')
    op.drop_table('extraction_snippets')
    op.drop_index(op.f('ix_duplicate_matches_extraction_id'), table_name='duplicate_matches')
    op.drop_table('duplicate_matches')
    op.drop_index(op.f('ix_extraction_results_status'), table_name='extraction_results')
    op.drop_index(op.f('ix_extraction_results_fingerprint'), table_name='extraction_results')
    op.drop_index(op.f('ix_extraction_results_external_user_id'), table_name='extraction_results')
    op.drop_index(op.f('ix_extraction_results_email_id'), table_name='extraction_results')
    op.drop_table('extraction_results')
    op.drop_index(op.f('ix_email_classifications_email_id'), table_name='email_classifications')
    op.drop_table('email_classifications')
    op.drop_index(op.f('ix_webhook_outbox_status'), table_name='webhook_outbox')
    op.drop_index(op.f('ix_webhook_outbox_next_attempt_at'), table_name='webhook_outbox')
    op.drop_table('webhook_outbox')
    op.drop_table('webhook_config')
    op.drop_table('merchant_rules')
    op.drop_index('uq_imported_emails_alias_message', table_name='imported_emails', postgresql_where="message_id IS NOT NULL AND message_id != ''")
    op.drop_index(op.f('ix_imported_emails_status'), table_name='imported_emails')
    op.drop_index(op.f('ix_imported_emails_alias_hash'), table_name='imported_emails')
    op.drop_table('imported_emails')
    op.drop_index(op.f('ix_import_audit_logs_email_id'), table_name='import_audit_logs')
    op.drop_table('import_audit_logs')
    op.drop_table('extraction_templates')
    op.drop_index(op.f('ix_category_feedback_log_merchant_normalized'), table_name='category_feedback_log')
    op.drop_index(op.f('ix_category_feedback_log_extraction_id'), table_name='category_feedback_log')
    op.drop_table('category_feedback_log')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_aliases_external_user_id'), table_name='aliases')
    op.drop_index(op.f('ix_aliases_alias_hash'), table_name='aliases')
    op.drop_table('aliases')
    # ### end Alembic commands ###
