"""pending_deletion_at

Revision ID: d34a3504ce8d
Revises: 43bc4967a755
Create Date: 2026-08-05 21:36:52.356056

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'd34a3504ce8d'
down_revision = '43bc4967a755'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imported_emails', sa.Column('pending_deletion_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_imported_emails_pending_deletion_at'), 'imported_emails', ['pending_deletion_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_imported_emails_pending_deletion_at'), table_name='imported_emails')
    op.drop_column('imported_emails', 'pending_deletion_at')
    # ### end Alembic commands ###
